import { useEffect, useState } from "react";
import { useParams, Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, Plus, Calendar, DollarSign, Users, CheckSquare, Pencil, Sparkles } from "lucide-react";
import useProjectStore from "../../store/projectStore";
import useAiStore from "../../store/aiStore";
import Badge from "../../components/ui/Badge";
import ProgressBar from "../../components/ui/ProgressBar";
import Button from "../../components/ui/Button";
import Modal from "../../components/ui/Modal";
import Input from "../../components/ui/Input";
import Select from "../../components/ui/Select";
import Tabs from "../../components/ui/Tabs";
import Spinner from "../../components/common/Spinner";
import KanbanBoard from "../../components/projects/KanbanBoard";
import { formatDate, formatCurrency } from "../../utils/helpers";
import api from "../../services/api";
import toast from "react-hot-toast";

const TASK_PRIORITIES = [
  { value: "low", label: "Low" }, { value: "medium", label: "Medium" },
  { value: "high", label: "High" }, { value: "urgent", label: "Urgent" },
];

const TaskForm = ({ projectId, onSubmit, onClose, loading }) => {
  const [form, setForm] = useState({ title: "", description: "", priority: "medium", dueDate: "", projectId });
  const set = (e) => setForm((f) => ({ ...f, [e.target.name]: e.target.value }));
  return (
    <form onSubmit={(e) => { e.preventDefault(); onSubmit(form); }} className="space-y-4">
      <Input label="Task title *" name="title" placeholder="e.g. Design homepage mockup" value={form.title} onChange={set} required />
      <div>
        <label className="label">Description</label>
        <textarea name="description" className="input resize-none h-16" placeholder="Optional details..." value={form.description} onChange={set} />
      </div>
      <div className="grid grid-cols-2 gap-3">
        <Select label="Priority" name="priority" value={form.priority} onChange={set} options={TASK_PRIORITIES} />
        <Input label="Due date" name="dueDate" type="date" value={form.dueDate} onChange={set} />
      </div>
      <div className="flex gap-3 pt-2">
        <Button type="button" variant="secondary" className="flex-1" onClick={onClose}>Cancel</Button>
        <Button type="submit" className="flex-1" loading={loading}>Add Task</Button>
      </div>
    </form>
  );
};

const ProjectDetail = () => {
  const { id } = useParams();
  const { currentProject, tasks, fetchProject, fetchTasks, createTask, updateProject, isLoading } = useProjectStore();
  const { sendMessage } = useAiStore();
  const [tab, setTab]             = useState("kanban");
  const [taskModal, setTaskModal] = useState(false);
  const [addingTask, setAddingTask] = useState(false);
  const [aiLoading, setAiLoading]   = useState(false);

  useEffect(() => {
    fetchProject(id);
    fetchTasks(id);
  }, [id]);

  const handleAddTask = async (form) => {
    setAddingTask(true);
    await createTask(form);
    setAddingTask(false);
    setTaskModal(false);
  };

  const handleAiTasks = async () => {
    if (!currentProject) return;
    setAiLoading(true);
    try {
      const { data } = await api.get(`/projects/${id}/ai-tasks`);
      const suggested = data.data.tasks || [];
      // Bulk create suggested tasks
      await Promise.all(
        suggested.map((t) => createTask({ ...t, projectId: id }))
      );
      toast.success(`${suggested.length} tasks generated by AI`);
    } catch {
      toast.error("AI task generation failed");
    } finally {
      setAiLoading(false);
    }
  };

  if (isLoading && !currentProject) return <Spinner size="lg" className="min-h-[60vh]" />;
  if (!currentProject) return null;

  const p = currentProject;
  const TABS = [
    { id: "kanban",  label: "Kanban",   icon: CheckSquare, count: tasks.length },
    { id: "overview", label: "Overview", icon: DollarSign },
  ];

  return (
    <div className="p-6 lg:p-8 max-w-7xl mx-auto">
      <Link to="/projects" className="flex items-center gap-1.5 text-sm text-ink-secondary hover:text-ink mb-6 transition-colors">
        <ArrowLeft size={14} /> Back to projects
      </Link>

      {/* Header */}
      <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }}
        className="flex flex-wrap items-start justify-between gap-4 mb-6">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3 mb-1">
            <h1 className="text-2xl font-bold text-ink dark:text-slate-100 truncate">{p.title}</h1>
            <Badge status={p.status} dot />
          </div>
          {p.description && <p className="text-sm text-ink-secondary line-clamp-2">{p.description}</p>}
        </div>
        <div className="flex items-center gap-2">
          <Button variant="secondary" size="sm" icon={<Pencil size={13} />}>Edit</Button>
          <Button variant="secondary" size="sm" icon={<Sparkles size={13} />} loading={aiLoading} onClick={handleAiTasks}>
            AI Tasks
          </Button>
          <Button size="sm" icon={<Plus size={14} />} onClick={() => setTaskModal(true)}>Add Task</Button>
        </div>
      </motion.div>

      {/* Meta row */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
        {[
          { icon: DollarSign, label: "Budget",   value: formatCurrency(p.budget, p.currency) },
          { icon: Calendar,   label: "Deadline",  value: formatDate(p.deadline) },
          { icon: CheckSquare,label: "Tasks",     value: `${p.taskStats?.done ?? 0}/${p.taskStats?.total ?? 0} done` },
          { icon: Users,      label: "Client",    value: p.clientId?.name || "—" },
        ].map(({ icon: Icon, label, value }) => (
          <div key={label} className="card py-3 px-4">
            <div className="flex items-center gap-2 mb-1">
              <Icon size={13} className="text-ink-muted" />
              <span className="text-xs text-ink-muted">{label}</span>
            </div>
            <p className="text-sm font-semibold text-ink dark:text-slate-200">{value}</p>
          </div>
        ))}
      </div>

      {/* Progress */}
      <div className="card mb-6">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm font-medium text-ink dark:text-slate-200">Overall Progress</span>
          <span className="text-sm font-bold text-brand">{p.progress ?? 0}%</span>
        </div>
        <ProgressBar value={p.progress ?? 0} size="lg" color={p.progress >= 100 ? "success" : "brand"} />
      </div>

      {/* Tabs */}
      <Tabs tabs={TABS} active={tab} onChange={setTab} className="mb-6 w-fit" />

      {tab === "kanban" && <KanbanBoard projectId={id} />}

      {tab === "overview" && (
        <div className="card">
          <h3 className="font-semibold text-ink dark:text-slate-100 mb-4">Task breakdown</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            {[
              { label: "To Do",       value: p.taskStats?.todo ?? 0,        color: "bg-slate-400" },
              { label: "In Progress", value: p.taskStats?.in_progress ?? 0, color: "bg-brand" },
              { label: "In Review",   value: p.taskStats?.review ?? 0,      color: "bg-warning" },
              { label: "Done",        value: p.taskStats?.done ?? 0,        color: "bg-success" },
            ].map(({ label, value, color }) => (
              <div key={label} className="text-center p-4 rounded-xl bg-surface-secondary dark:bg-dark-muted">
                <div className={`w-3 h-3 rounded-full ${color} mx-auto mb-2`} />
                <p className="text-2xl font-bold text-ink dark:text-slate-100">{value}</p>
                <p className="text-xs text-ink-muted">{label}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      <Modal isOpen={taskModal} onClose={() => setTaskModal(false)} title="New Task">
        <TaskForm projectId={id} onSubmit={handleAddTask} onClose={() => setTaskModal(false)} loading={addingTask} />
      </Modal>
    </div>
  );
};

export default ProjectDetail;
